SET PATH=D:\Development\1.Development_Tool\Keil_5\Core\ARM\ARMCC\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;D:\Development\1.Development_Tool\MinGW64\bin;C:\Program Files\dotnet\;D:\Development\1.Development_Tool\Cmake-3.22.1\bin;D:\Development\1.Development_Tool\Git\cmd;C:\Users\Roy\AppData\Local\Microsoft\WindowsApps;;E:\Software\Development\Microsoft VS Code\bin;C:\Users\Roy\.dotnet\tools
SET ARMCC5_ASMOPT=--diag_suppress=9931
SET ARMCC5_CCOPT=--diag_suppress=9931
SET ARMCC5_LINKOPT=--diag_suppress=9931
SET CPU_TYPE=M058LDN
SET CPU_VENDOR=Nuvoton
SET UV2_TARGET=SSD1306
SET CPU_CLOCK=0x00B71B00
